### ISSUE TITLE
Add russian translate to your extensions, please:

### ISSUE THREAD

**Issue by led9** [mkopec/close-tabs-to-the-right#7]
Close Tabs to the Right = in russian "Закрыть вкладки справа".
Close Other Tabs = in russian "Закрыть другие вкладки".
Dzięki za pomocne rozszerzenia!

**Comment by mkopec** [comment]
I just added a russian locale, thanks! Unfortunately I do not have write access to the Close Other Tabs repository so you'll have to ask there.
